name: CI FOR C4
on:
  push:
    paths-ignore:
      - ".github/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        env:
          NETFLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETFLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: yarn add
          yarn build
          npx netlify-cli deploy --dir=public --prod
