name: CI FOR C4
on:
  push:
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/**"
jobs:
  test:
    runs-on: ubuntu-latest

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and Run
        env:
          NETFLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETFLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run:
          - yarn add
          - yarn test
          - yarn build
          - npx netlify-cli deploy --dir=public --prod
